### ISSUE TITLE
syslog not availble for windows

### ISSUE THREAD

**Issue by willie68** [devopsfaith/krakend-gologging#3]
i try to build krakend for windows, but building failed. 
I just recognise, as far as i tested it, the only reason why krakend-ce build failed for windows is, that the logging is using syslog, which is not availble for windows and plan9. 
I would like to have a krakend as a windows binary.

(I just dig a little deeper in this issue and implemented a little work around, 2 src files with different build tags, one for windows without syslog and one for the rest.)

**Comment by myusri** [comment]
Hi @willie68, couldn't you issue a PR for your changes because it is useful to have krakend-ce running on Windows?

**Comment by willie68** [comment]
Hi,
i already did this, see https://github.com/devopsfaith/krakend-gologging/pull/4

**Comment by myusri** [comment]
Sorry, my bad. I didn't notice it because your PR is closed already. You closed it because the maintainer doesn't want to support Windows?

Anyway, it does seem like syslog support have been removed from `log.go` for non-Windows built, as mentioned in https://github.com/devopsfaith/krakend-gologging/pull/4#issuecomment-601115294.

**Comment by willie68** [comment]
Yes, that was the main reason.
But can't see any changes on the master branch... But, if you need this, you can simply use the files on my fork.

**Comment by kpacha** [comment]
before closing this, I want to extend my point at the linked discussion: we don't have the resources to keep all the features available on every OS/arch or to manage several production-ready versions with different sets of features/behaviours. that's why we decided to just support gnu/linux environments for production and gnu/linux and osx envs for devel.

this is not me telling you "you should not use windows", this is me suggesting you "if you're on windows, try krakend via docker".

**Comment by willie68** [comment]
Thats ok for me. No problem. The idea behind windows support for me ( and i think i'm not the only one)  is, that i had to develop software on windows (Company policy). On our side it is not planned to run this software productively on Windows. Our productive cloud stack is based on kubernetes/docker, so everything is fine.
